services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Using external AWS RDS instance
      - DATABASE_URL=postgresql://qaraj_app:qaraj_app7162381637@servicewebhooks.cp08geg2csn4.us-east-1.rds.amazonaws.com:5432/qaraj
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
