import type { ServiceType, CarForSale, ServiceRecord } from './types';
import { TFunction } from 'i18next';

export const carBrands = [
  { value: 'BYD', label: 'BYD' },
  { value: 'Ford', label: 'Ford' },
  { value: 'Honda', label: 'Honda' },
  { value: 'Mazda', label: 'Mazda' },
  { value: 'Mitsubishi', label: 'Mitsubishi' },
  { value: 'Subaru', label: 'Subaru' },
  { value: 'Toyota', label: 'Toyota' },
];

export const carModels: Record<string, { value: string; label: string }[]> = {
  BYD: [
    { value: 'Atto 3', label: 'Atto 3' },
    { value: 'Chazor', label: 'Chazor' },
    { value: 'Destroyer', label: 'Destroyer' },
    { value: 'Dolphin', label: 'Dolphin' },
    { value: 'Han', label: 'Han' },
    { value: 'Leopard', label: 'Leopard' },
    { value: 'Qin Plus', label: 'Qin Plus' },
    { value: 'Seal', label: 'Seal' },
    { value: 'Seal U', label: 'Seal U' },
    { value: 'Sealion 7', label: 'Sealion 7' },
    { value: 'Shark', label: 'Shark' },
    { value: 'Song Plus', label: 'Song Plus' },
    { value: 'Tang', label: 'Tang' },
    { value: 'Yuan Plus', label: 'Yuan Plus' },
  ],
  Mitsubishi: [
    { value: 'ASX', label: 'ASX' },
    { value: 'Attrage', label: 'Attrage' },
    { value: 'Eclipse Cross', label: 'Eclipse Cross' },
    { value: 'Gallant', label: 'Gallant' },
    { value: 'Lancer', label: 'Lancer' },
    { value: 'Mirage', label: 'Mirage' },
    { value: 'Mirage G4', label: 'Mirage G4' },
    { value: 'Outlander', label: 'Outlander' },
    { value: 'Outlander PHEV', label: 'Outlander PHEV' },
    { value: 'Outlander Sport', label: 'Outlander Sport' },
    { value: 'Pajero', label: 'Pajero' },
    { value: 'Pajero Sport', label: 'Pajero Sport' },
    { value: 'Triton / L200', label: 'Triton / L200' },
  ],
  Subaru: [
    { value: 'Ascent', label: 'Ascent' },
    { value: 'BRZ', label: 'BRZ' },
    { value: 'Crosstrek', label: 'Crosstrek' },
    { value: 'Forester', label: 'Forester' },
    { value: 'Impreza', label: 'Impreza' },
    { value: 'Legacy', label: 'Legacy' },
    { value: 'Outback', label: 'Outback' },
    { value: 'Solterra', label: 'Solterra' },
    { value: 'Tribeca', label: 'Tribeca' },
    { value: 'XV', label: 'XV' },
  ],
  Toyota: [
    { value: '4Runner', label: '4Runner' },
    { value: 'Avalon', label: 'Avalon' },
    { value: 'bZ4X', label: 'bZ4X' },
    { value: 'C-HR', label: 'C-HR' },
    { value: 'Camry', label: 'Camry' },
    { value: 'Corolla', label: 'Corolla' },
    { value: 'Corolla Cross', label: 'Corolla Cross' },
    { value: 'Crown', label: 'Crown' },
    { value: 'FJ Cruiser', label: 'FJ Cruiser' },
    { value: 'Fortuner', label: 'Fortuner' },
    { value: 'Grand Highlander', label: 'Grand Highlander' },
    { value: 'Hiace', label: 'Hiace' },
    { value: 'Highlander', label: 'Highlander' },
    { value: 'Hilux', label: 'Hilux' },
    { value: 'Land Cruiser', label: 'Land Cruiser' },
    { value: 'Land Cruiser Prado', label: 'Land Cruiser Prado' },
    { value: 'Prius', label: 'Prius' },
    { value: 'RAV4', label: 'RAV4' },
    { value: 'Sequoia', label: 'Sequoia' },
    { value: 'Tacoma', label: 'Tacoma' },
    { value: 'Tundra', label: 'Tundra' },
    { value: 'Venza', label: 'Venza' },
    { value: 'Yaris', label: 'Yaris' },
    { value: 'Yaris Cross', label: 'Yaris Cross' },
  ],
  Mazda: [
    { value: 'CX-3', label: 'CX-3' },
    { value: 'CX-5', label: 'CX-5' },
    { value: 'CX-7', label: 'CX-7' },
    { value: 'CX-9', label: 'CX-9' },
    { value: 'CX-30', label: 'CX-30' },
    { value: 'CX-50', label: 'CX-50' },
    { value: 'CX-60', label: 'CX-60' },
    { value: 'CX-70', label: 'CX-70' },
    { value: 'CX-80', label: 'CX-80' },
    { value: 'CX-90', label: 'CX-90' },
    { value: 'EZ-60', label: 'EZ-60' },
    { value: 'Mazda2', label: 'Mazda2' },
    { value: 'Mazda3', label: 'Mazda3' },
    { value: 'Mazda6', label: 'Mazda6' },
    { value: 'MX-5', label: 'MX-5' },
  ],
  Ford: [
    { value: 'Bronco', label: 'Bronco' },
    { value: 'Bronco Sport', label: 'Bronco Sport' },
    { value: 'Courier', label: 'Courier' },
    { value: 'Custom', label: 'Custom' },
    { value: 'EcoSport', label: 'EcoSport' },
    { value: 'Edge', label: 'Edge' },
    { value: 'Escape (Kuga)', label: 'Escape (Kuga)' },
    { value: 'Expedition', label: 'Expedition' },
    { value: 'Explorer', label: 'Explorer' },
    { value: 'F-150', label: 'F-150' },
    { value: 'Fiesta', label: 'Fiesta' },
    { value: 'Focus', label: 'Focus' },
    { value: 'Fusion', label: 'Fusion' },
    { value: 'Maverick', label: 'Maverick' },
    { value: 'Mondeo', label: 'Mondeo' },
    { value: 'Mustang', label: 'Mustang' },
    { value: 'Mustang Mach-E', label: 'Mustang Mach-E' },
    { value: 'Puma', label: 'Puma' },
    { value: 'Ranger', label: 'Ranger' },
    { value: 'Super Duty', label: 'Super Duty' },
    { value: 'Transit', label: 'Transit' },
  ],
  Honda: [
    { value: 'Accord', label: 'Accord' },
    { value: 'City', label: 'City' },
    { value: 'Civic', label: 'Civic' },
    { value: 'CR-V', label: 'CR-V' },
    { value: 'e:NS', label: 'e:NS' },
    { value: 'Fit / Jazz', label: 'Fit / Jazz' },
    { value: 'HR-V', label: 'HR-V' },
    { value: 'Insight', label: 'Insight' },
    { value: 'Odyssey', label: 'Odyssey' },
    { value: 'Passport', label: 'Passport' },
    { value: 'Pilot', label: 'Pilot' },
    { value: 'Ridgeline', label: 'Ridgeline' },
  ],
};

export const carYears = Array.from({ length: 30 }, (_, i) => {
  const year = new Date().getFullYear() - i;
  return { value: year.toString(), label: year.toString() };
});

const getServiceTranslation = (t: TFunction, serviceId: string, field: 'name' | 'description' | 'fullDescription' | 'includes') => {
  const serviceMap: Record<string, any> = {
    '1': {
      name: t('home.oilChangeName'),
      description: t('home.oilChangeDesc'),
      fullDescription: t('home.oilChangeFull'),
      includes: [
        t('home.oilChangeInclude1'),
        t('home.oilChangeInclude2'),
        t('home.oilChangeInclude3'),
        t('home.oilChangeInclude4'),
        t('home.oilChangeInclude5'),
        t('home.oilChangeInclude6'),
      ],
    },
    '2': {
      name: t('home.fullInspectionName'),
      description: t('home.fullInspectionDesc'),
      fullDescription: t('home.fullInspectionFull'),
      includes: [
        t('home.fullInspectionInclude1'),
        t('home.fullInspectionInclude2'),
        t('home.fullInspectionInclude3'),
        t('home.fullInspectionInclude4'),
        t('home.fullInspectionInclude5'),
        t('home.fullInspectionInclude6'),
      ],
    },
    '3': {
      name: t('home.brakeServiceName'),
      description: t('home.brakeServiceDesc'),
      fullDescription: t('home.brakeServiceFull'),
      includes: [
        t('home.brakeServiceInclude1'),
        t('home.brakeServiceInclude2'),
        t('home.brakeServiceInclude3'),
        t('home.brakeServiceInclude4'),
        t('home.brakeServiceInclude5'),
        t('home.brakeServiceInclude6'),
      ],
    },
    '4': {
      name: t('home.tireServiceName'),
      description: t('home.tireServiceDesc'),
      fullDescription: t('home.tireServiceFull'),
      includes: [
        t('home.tireServiceInclude1'),
        t('home.tireServiceInclude2'),
        t('home.tireServiceInclude3'),
        t('home.tireServiceInclude4'),
        t('home.tireServiceInclude5'),
        t('home.tireServiceInclude6'),
      ],
    },
    '5': {
      name: t('home.batteryServiceName'),
      description: t('home.batteryServiceDesc'),
      fullDescription: t('home.batteryServiceFull'),
      includes: [
        t('home.batteryServiceInclude1'),
        t('home.batteryServiceInclude2'),
        t('home.batteryServiceInclude3'),
        t('home.batteryServiceInclude4'),
        t('home.batteryServiceInclude5'),
        t('home.batteryServiceInclude6'),
      ],
    },
    '6': {
      name: t('home.airConditioningName'),
      description: t('home.airConditioningDesc'),
      fullDescription: t('home.airConditioningFull'),
      includes: [
        t('home.airConditioningInclude1'),
        t('home.airConditioningInclude2'),
        t('home.airConditioningInclude3'),
        t('home.airConditioningInclude4'),
        t('home.airConditioningInclude5'),
        t('home.airConditioningInclude6'),
      ],
    },
  };

  return serviceMap[serviceId]?.[field];
};

export const getTranslatedServices = (t: TFunction): ServiceType[] => [
  {
    id: '1',
    name: t('home.oilChangeName'),
    description: t('home.oilChangeDesc'),
    icon: 'wrench',
    price: 120,
    duration: '45 min',
    imageUri: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80',
    fullDescription: t('home.oilChangeFull'),
    includes: [
      t('home.oilChangeInclude1'),
      t('home.oilChangeInclude2'),
      t('home.oilChangeInclude3'),
      t('home.oilChangeInclude4'),
      t('home.oilChangeInclude5'),
      t('home.oilChangeInclude6'),
    ],
  },
  {
    id: '2',
    name: t('home.fullInspectionName'),
    description: t('home.fullInspectionDesc'),
    icon: 'check-circle',
    price: 95,
    duration: '90 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/zgf2l7itgqb9hvjm3s71k',
    fullDescription: t('home.fullInspectionFull'),
    includes: [
      t('home.fullInspectionInclude1'),
      t('home.fullInspectionInclude2'),
      t('home.fullInspectionInclude3'),
      t('home.fullInspectionInclude4'),
      t('home.fullInspectionInclude5'),
      t('home.fullInspectionInclude6'),
    ],
  },
  {
    id: '3',
    name: t('home.brakeServiceName'),
    description: t('home.brakeServiceDesc'),
    icon: 'wrench',
    price: 380,
    duration: '2 hours',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/2i0qs6u9pc35z79dfr9f5',
    fullDescription: t('home.brakeServiceFull'),
    includes: [
      t('home.brakeServiceInclude1'),
      t('home.brakeServiceInclude2'),
      t('home.brakeServiceInclude3'),
      t('home.brakeServiceInclude4'),
      t('home.brakeServiceInclude5'),
      t('home.brakeServiceInclude6'),
    ],
  },
  {
    id: '4',
    name: t('home.tireServiceName'),
    description: t('home.tireServiceDesc'),
    icon: 'check-circle',
    price: 85,
    duration: '60 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/4zxqt0guv64ibvtchv9k7',
    fullDescription: t('home.tireServiceFull'),
    includes: [
      t('home.tireServiceInclude1'),
      t('home.tireServiceInclude2'),
      t('home.tireServiceInclude3'),
      t('home.tireServiceInclude4'),
      t('home.tireServiceInclude5'),
      t('home.tireServiceInclude6'),
    ],
  },
  {
    id: '5',
    name: t('home.batteryServiceName'),
    description: t('home.batteryServiceDesc'),
    icon: 'wrench',
    price: 245,
    duration: '30 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/ftlz23p1ku2iv6oozptvs',
    fullDescription: t('home.batteryServiceFull'),
    includes: [
      t('home.batteryServiceInclude1'),
      t('home.batteryServiceInclude2'),
      t('home.batteryServiceInclude3'),
      t('home.batteryServiceInclude4'),
      t('home.batteryServiceInclude5'),
      t('home.batteryServiceInclude6'),
    ],
  },
  {
    id: '6',
    name: t('home.airConditioningName'),
    description: t('home.airConditioningDesc'),
    icon: 'check-circle',
    price: 195,
    duration: '90 min',
    imageUri: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80',
    fullDescription: t('home.airConditioningFull'),
    includes: [
      t('home.airConditioningInclude1'),
      t('home.airConditioningInclude2'),
      t('home.airConditioningInclude3'),
      t('home.airConditioningInclude4'),
      t('home.airConditioningInclude5'),
      t('home.airConditioningInclude6'),
    ],
  },
];

export const serviceTypes: ServiceType[] = [
  {
    id: '1',
    name: 'Oil Change',
    description: 'Regular maintenance',
    icon: 'wrench',
    price: 120,
    duration: '45 min',
    imageUri: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80',
    fullDescription: 'Complete engine oil and filter replacement service using premium quality oils. Includes multi-point inspection, fluid level check, and tire pressure adjustment.',
    includes: [
      'Premium quality engine oil',
      'Oil filter replacement',
      'Multi-point inspection',
      'Fluid level check',
      'Tire pressure adjustment',
      'Vehicle wash',
    ],
  },
  {
    id: '2',
    name: 'Full Inspection',
    description: 'Full vehicle check',
    icon: 'check-circle',
    price: 95,
    duration: '90 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/zgf2l7itgqb9hvjm3s71k',
    fullDescription: 'Comprehensive 150-point vehicle inspection covering all major systems. Get a detailed report on your vehicle\'s condition with expert recommendations.',
    includes: [
      '150-point comprehensive check',
      'Brake system inspection',
      'Suspension analysis',
      'Electrical system check',
      'Engine diagnostics',
      'Detailed condition report',
    ],
  },
  {
    id: '3',
    name: 'Brake Service',
    description: 'Brake repair & replacement',
    icon: 'wrench',
    price: 380,
    duration: '2 hours',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/2i0qs6u9pc35z79dfr9f5',
    fullDescription: 'Professional brake service including pad replacement, rotor resurfacing or replacement, and complete brake system check for optimal stopping power.',
    includes: [
      'Brake pad replacement',
      'Rotor inspection & resurfacing',
      'Brake fluid check/replacement',
      'Caliper inspection',
      'Brake line inspection',
      'Test drive verification',
    ],
  },
  {
    id: '4',
    name: 'Tire Service',
    description: 'Rotation & replacement',
    icon: 'check-circle',
    price: 85,
    duration: '60 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/4zxqt0guv64ibvtchv9k7',
    fullDescription: 'Complete tire service including rotation, balancing, and alignment. Extends tire life and ensures optimal vehicle handling and fuel efficiency.',
    includes: [
      'Tire rotation',
      'Wheel balancing',
      'Alignment check',
      'Tire pressure adjustment',
      'Tread depth measurement',
      'Visual tire inspection',
    ],
  },
  {
    id: '5',
    name: 'Battery Service',
    description: 'Testing & replacement',
    icon: 'wrench',
    price: 245,
    duration: '30 min',
    imageUri: 'https://pub-e001eb4506b145aa938b5d3badbff6a5.r2.dev/attachments/ftlz23p1ku2iv6oozptvs',
    fullDescription: 'Complete battery testing, cleaning, and replacement service. Includes charging system check to ensure your vehicle starts reliably every time.',
    includes: [
      'Battery load test',
      'Terminal cleaning',
      'Charging system check',
      'Battery replacement (if needed)',
      'Warranty registration',
      'Free retest in 6 months',
    ],
  },
  {
    id: '6',
    name: 'Air Conditioning',
    description: 'AC service & repair',
    icon: 'check-circle',
    price: 195,
    duration: '90 min',
    imageUri: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80',
    fullDescription: 'Professional AC service including refrigerant recharge, leak detection, and system performance check for optimal cooling comfort.',
    includes: [
      'AC system diagnostics',
      'Refrigerant level check',
      'Leak detection',
      'Filter replacement',
      'System performance test',
      'Cabin air quality check',
    ],
  },
];

export const carsForSale: CarForSale[] = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Camry',
    year: 2024,
    price: 55275,
    mileage: 0,
    fuelType: 'Hybrid',
    condition: 'new',
    imageUri: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
  },
  {
    id: '2',
    brand: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 49130,
    mileage: 15000,
    fuelType: 'Gasoline',
    condition: 'pre-owned',
    imageUri: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
  },
];

export const serviceCenters = [
  {
    id: '1',
    name: 'Toyota Abşeron Mərkəzi',
    address: 'Bakı-Sumqayıt şossesi 6-cı km',
    phone: '+994123490060',
    phoneDisplay: '012 349 00 60',
    shortCode: '*0110',
    rating: 5.0,
    lat: 40.4897,
    lng: 49.8647,
    imageUri: 'http://91.107.161.67:3000/static/service-centers/toyota-absheron.webp',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Toyota+Absheron+Baku+Sumgait+highway+6km',
    website: 'https://groupmotors.az',
    brands: ['Toyota'],
    workingHours: {
      sales: 'Mon-Sat 09:00-18:00, Sun 10:00-16:00',
      service: 'Mon-Sat 09:00-18:00',
    },
    services: ['Oil Change', 'Brake Service', 'Full Inspection', 'Tire Service', 'Air Conditioning', 'Battery Service', 'Wheel Alignment'],
  },
  {
    id: '2',
    name: 'Mitsubishi Motors',
    address: 'Bakı-Sumqayıt şossesi 6-cı km, Babək pr. 33',
    phone: '+994123490006',
    phoneDisplay: '012 349 00 06',
    shortCode: '*5665',
    rating: 5.0,
    lat: 40.4897,
    lng: 49.8647,
    imageUri: 'http://91.107.161.67:3000/static/service-centers/mitsubishi-motors.webp',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mitsubishi+Motors+Baku+Sumgait+highway+6km',
    website: 'https://mitsubishi-motors.az',
    brands: ['Mitsubishi'],
    workingHours: {
      sales: 'Mon-Sat 09:00-18:00, Sun 10:00-16:00',
      service: 'Mon-Sat 09:00-18:00',
    },
    services: ['Oil Change', 'Brake Service', 'Full Inspection', 'Tire Service', 'Air Conditioning', 'Battery Service', 'Wheel Alignment'],
  },
  {
    id: '3',
    name: 'Mazda Azərbaycan',
    address: 'Bakı-Sumqayıt şossesi 6-cı km, Babək pr. 33',
    phone: '+994123490100',
    phoneDisplay: '012 349 01 00',
    shortCode: '*5665',
    rating: 5.0,
    lat: 40.4897,
    lng: 49.8647,
    imageUri: 'http://91.107.161.67:3000/static/service-centers/mazda-azerbaijan.webp',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mazda+Azerbaijan+Baku+Sumgait+highway+6km',
    website: 'https://mazda.az',
    brands: ['Mazda'],
    workingHours: {
      sales: 'Mon-Sat 09:00-18:00, Sun 10:00-16:00',
      service: 'Mon-Sat 09:00-18:00',
    },
    services: ['Oil Change', 'Brake Service', 'Full Inspection', 'Tire Service', 'Air Conditioning', 'Battery Service', 'Wheel Alignment'],
  },
  {
    id: '4',
    name: 'Toyota Gəncə Mərkəzi',
    address: 'Gəncə-Şəmkir şossesi 1-ci km',
    phone: '+994222592525',
    phoneDisplay: '022 259 25 25',
    secondaryPhone: '+994103402020',
    secondaryPhoneDisplay: '010 340 20 20',
    rating: 5.0,
    lat: 40.6828,
    lng: 46.3406,
    imageUri: 'http://91.107.161.67:3000/static/service-centers/toyota-ganja.webp',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Toyota+Ganja+Shamkir+highway',
    website: 'https://groupmotors.az',
    brands: ['Toyota'],
    workingHours: {
      sales: 'Mon-Fri 09:00-17:00, Sat 09:00-15:00',
      service: 'Mon-Sat 09:00-18:00',
    },
    services: ['Oil Change', 'Brake Service', 'Full Inspection', 'Tire Service', 'Air Conditioning', 'Battery Service', 'Wheel Alignment'],
  },
  {
    id: '5',
    name: 'BYD Abşeron Mərkəzi',
    address: 'Bakı-Sumqayıt şossesi 6-cı km',
    phone: '*969',
    phoneDisplay: '*969',
    rating: 5.0,
    lat: 40.4897,
    lng: 49.8647,
    imageUri: 'http://91.107.161.67:3000/static/service-centers/byd-absheron.webp',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=BYD+Absheron+Baku+Sumgait+highway+6km',
    website: 'https://groupmotors.az',
    brands: ['BYD'],
    workingHours: {
      sales: 'Mon-Sat 09:00-18:00, Sun 10:00-16:00',
      service: 'Mon-Sat 09:00-18:00',
    },
    services: ['Oil Change', 'Brake Service', 'Full Inspection', 'Tire Service', 'Air Conditioning', 'Battery Service', 'Wheel Alignment'],
  },
];

export const mockServiceRecords: ServiceRecord[] = [
  {
    id: '1',
    vehicleId: '1',
    serviceName: 'Annual Inspection & Oil Change',
    serviceType: 'maintenance',
    date: '2024-08-15',
    mileage: 45200,
    cost: 323,
    serviceCenter: 'ACar Service Center - Downtown',
    technician: 'John Smith',
    partsUsed: ['Engine Oil 5W-30 (5L)', 'Oil Filter', 'Air Filter'],
    notes: 'Vehicle passed inspection. Recommended brake fluid change in 6 months.',
    createdAt: '2024-08-15',
  },
  {
    id: '2',
    vehicleId: '1',
    serviceName: 'Brake Pad Replacement',
    serviceType: 'repair',
    date: '2024-05-22',
    mileage: 42800,
    cost: 486,
    serviceCenter: 'ACar Service Center - Downtown',
    technician: 'Mike Johnson',
    partsUsed: ['Front Brake Pads', 'Brake Fluid'],
    notes: 'Front brake pads replaced. Rear brakes still in good condition.',
    createdAt: '2024-05-22',
  },
  {
    id: '3',
    vehicleId: '1',
    serviceName: 'Tire Rotation & Wheel Alignment',
    serviceType: 'maintenance',
    date: '2024-02-10',
    mileage: 38500,
    cost: 213,
    serviceCenter: 'ACar Service Center - Downtown',
    technician: 'Sarah Davis',
    partsUsed: [],
    notes: 'All tires rotated. Wheel alignment adjusted to factory specifications.',
    createdAt: '2024-02-10',
  },
];
